name: crucible-ci

on:
  # run on push or pull request events for the main branch only
  pull_request:
    branches: [ main ]

  # allow for manual invocation from the actions tab
  workflow_dispatch:

jobs:
  crucible-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout bench-iperf
      uses: actions/checkout@v2
      with:
        path: bench-iperf

    - name: Checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci

    - name: Run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "iperf"
        ci_target: "iperf"
        ci_target_dir: ${{ github.workspace }}/bench-iperf
        scenarios: "iperf"
        repeat_runs: "yes"
        run_samples: "1"
        userenvs: "all"
